version: '3.7'
services:
  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-d.sql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: 123
